// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgX0TwV5dQd4gdDtYrcNdKVLwsy1RMOI4',
    appId: '1:618880525773:web:db86af3f25c950a8dfd084',
    messagingSenderId: '618880525773',
    projectId: 'solofirstgp',
    authDomain: 'solofirstgp.firebaseapp.com',
    storageBucket: 'solofirstgp.appspot.com',
    measurementId: 'G-EPLFKWHDMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJft9-_ptT5a2-PhsM_yWUttunKppPelA',
    appId: '1:618880525773:android:4221a5742586a6b1dfd084',
    messagingSenderId: '618880525773',
    projectId: 'solofirstgp',
    storageBucket: 'solofirstgp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuChlhpMSL0XCtBpry4oNn3gzrD5o1734',
    appId: '1:618880525773:ios:e69139dafd69147adfd084',
    messagingSenderId: '618880525773',
    projectId: 'solofirstgp',
    storageBucket: 'solofirstgp.appspot.com',
    iosClientId: '618880525773-hc82qkurjf5jk64tqpt1d72tup8unhd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.soloGameProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuChlhpMSL0XCtBpry4oNn3gzrD5o1734',
    appId: '1:618880525773:ios:e69139dafd69147adfd084',
    messagingSenderId: '618880525773',
    projectId: 'solofirstgp',
    storageBucket: 'solofirstgp.appspot.com',
    iosClientId: '618880525773-hc82qkurjf5jk64tqpt1d72tup8unhd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.soloGameProject',
  );
}
